### PR TITLE
Remove emmet-core down-pin causing ecosystem clash

### PR DESCRIPTION
**Pull request by janosh**
the down-pin on `emmet-core` [causes incompatibility with `atomate2`](https://github.com/materialsproject/atomate2/actions/runs/12215592714/job/34077711264?pr=1079) in https://github.com/materialsproject/atomate2/pull/1079:

```
 × No solution found when resolving dependencies:
  ╰─▶ Because mattersim==1.0.0rc9 depends on emmet-core<0.84 and
      atomate2[strict-forcefields]==0.0.1 depends on mattersim==1.0.0rc9,
      we can conclude that atomate2[strict-forcefields]==0.0.1 depends on
      emmet-core<0.84.
      And because atomate2==0.0.1 depends on emmet-core>=0.84.3rc3, we can
      conclude that atomate2[strict-forcefields]==0.0.1 is incompatible.
      And because only atomate2[strict-forcefields]==0.0.1 is available and
      you require atomate2[strict-forcefields], we can conclude that your
      requirements are unsatisfiable.
```

this PR changes the max-version to a min-version for `emmet-core` and removes all strict pins (`==` -> `>=`) to make `mattersim` more flexible and less likely to clash with other packages

### CODE REVIEW

**Comment by yanghan234** [comment]
Thank you, @janosh. I will test to see if this causes any conflicts in our repository. Please stay tuned.

**Review by yanghan234 — APPROVED** [review]

**Comment by janosh** [comment]
Thanks for merging! Could we get a new release to unblock atomate2 integration?

**Comment by yanghan234** [comment]
Hi @janosh, I just released a release candidate. Please try it in atomate2 and see if it works now. Let me know if further modification is needed.

**Comment by janosh** [comment]
thanks @yanghan234. looks like [the RC](https://pypi.org/project/mattersim/1.0.1rc1) solved the issue. 👍 

[there's still an incompatibility with `mace-torch`](https://github.com/materialsproject/atomate2/actions/runs/12470531565/job/34805829920) but i think that needs to be solved on the MACE side. pinging @ilyes319 to suggest a `mace-torch` release that relaxes the `e3nn` pin to `e3nn>=0.4.4`

```
  × No solution found when resolving dependencies:
  ╰─▶ Because mace-torch>=0.3.6 depends on e3nn==0.4.4 and only the following
      versions of mace-torch are available:
          mace-torch<=0.3.6
          mace-torch==0.3.7
          mace-torch==0.3.8
          mace-torch==0.3.9
      we can conclude that mace-torch>=0.3.6 depends on e3nn==0.4.4.
      And because mattersim==1.0.1rc1 depends on e3nn>=0.5.0, we can conclude
      that mace-torch>=0.3.6 and mattersim==1.0.1rc1 are incompatible.
```

**Pull request merged**
